# Generated by Django 5.0 on 2023-12-08 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="users",
            field=models.ManyToManyField(
                related_name="organisations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
