# Generated by Django 5.0 on 2023-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcel", "0002_organisation_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="id",
            field=models.CharField(
                editable=False, max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
