# Generated by Django 5.0 on 2023-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcel", "0004_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="id",
        ),
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(
                default="default", max_length=25, primary_key=True, serialize=False
            ),
        ),
    ]
