# Generated by Django 5.0 on 2023-12-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcel", "0005_remove_department_id_department_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
